name: SwiftPM Integration

on:
  push:
    branches:
      - master
      - dev
      - develop
  pull_request:
    branches:
      - master
      - dev
      - develop

env:
  DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

  IOS_SDK: iphonesimulator13.5
  IOS_DEST: "OS=13.5,name=iPhone 11"

  SCHEME: PROJECT

jobs:
  job-build:
    name: SwiftPM Build
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v1

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list

      - name: generate xcodeproj
        run: swift package generate-xcodeproj

      - name: Build
        run: |
          set -o pipefail
          xcodebuild clean build -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$IOS_DEST" | xcpretty -c
